swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /me/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transaction API
      description: API for fetching user's transactions
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User's transaction retrieved successfully
          schema:
            $ref: '#/definitions/TransactionsResponse'
        '401':
          description: Not Authorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
  /me/transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transaction API
      description: API for fetching an user's transaction
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          type: string
          name: transactionId
          description: Transaction ID to fetch
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User's transaction retrieved successfully
          schema:
            $ref: '#/definitions/Transaction'
        '401':
          description: Not Authorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    post:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transaction API
      description: API for creating an user's transaction
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          type: string
          name: transactionId
          description: Transaction ID to fetch
          required: true
        - in: body
          name: body
          description: Transaction payload
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      produces:
        - application/json
      responses:
        '200':
          description: User's transaction created successfully
          schema:
            $ref: '#/definitions/Transaction'
        '401':
          description: Not Authorized
        '500':
          description: Internal Server Error
    patch:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transaction API
      description: API for modifying an user's transaction
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          type: string
          name: transactionId
          description: Transaction ID to fetch
          required: true
        - in: body
          name: body
          description: Transaction payload
          schema:
            $ref: '#/definitions/Transaction'
      produces:
        - application/json
      responses:
        '200':
          description: User's transaction modified successfully
          schema:
            $ref: '#/definitions/Transaction'
        '401':
          description: Not Authorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transaction API
      description: API for deleting an user's transaction
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          type: string
          name: transactionId
          description: Transaction ID to fetch
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User's transaction deleted successfully
          schema:
            $ref: '#/definitions/Transaction'
        '401':
          description: Not Authorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Transaction:
    properties:
      id:
        type: string
        description: Transaction ID
      date:
        type: string
        description: Transaction date
      description:
        type: string
        description: Transaction description
      amount:
        type: number
        description: Transaction amount
      balance:
        type: number
        description: Account balance
      type:
        type: string
        description: Transaction type
      category:
        type: string
        description: Transaction category
      notes:
        type: string
        description: Transaction notes
  TransactionsResponse:
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/Transaction'
